version: "3.8"

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./whatsapp-session:/usr/src/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
